version: 1
tag_space: 64M
extend_limits: true
scenarios:
  - keymind/helljumper/levels/campaign/deployment_system/deployment_system
commands:
  release:
    - mercury build --release --output package/game-maps/